services:
  db:
    image: postgres:14
    container_name: podcity-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: podcity_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: podcity
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
