# Generated by Django 3.2.9 on 2021-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("link", models.URLField()),
                ("image", models.URLField()),
                ("podcast_name", models.CharField(max_length=255)),
                ("guid", models.CharField(max_length=50)),
            ],
        ),
    ]
